#ifndef __INTERFACEVERSION_H__
#define __INTERFACEVERSION_H__
//We include a file from the STL here in order to ensure _CPPLIB_VER has been defined
//#include <string>

//#ifndef _CPPLIB_VER
//#define EXODUS_STLVERSIONNO 0x0
//#define EXODUS_INTERFACEVERSION_MT 0x0
//#define EXODUS_INTERFACEVERSION_DLL 0x0
//#define EXODUS_INTERFACEVERSION_DEBUG 0x0
//#else
//#define EXODUS_STLBUILDNO _CPPLIB_VER
//#ifdef _MT
//#define EXODUS_INTERFACEVERSION_MT 0x80000000
//#else
//#define EXODUS_INTERFACEVERSION_MT 0x0
//#endif
//#ifdef _DLL
//#define EXODUS_INTERFACEVERSION_DLL 0x40000000
//#else
//#define EXODUS_INTERFACEVERSION_DLL 0x0
//#endif
//#ifdef _DEBUG
//#define EXODUS_INTERFACEVERSION_DEBUG 0x20000000
//#else
//#define EXODUS_INTERFACEVERSION_DEBUG 0x0
//#endif
//#endif

#define EXODUS_INTERFACEVERSION 1
//#define EXODUS_STLVERSION EXODUS_STLBUILDNO + EXODUS_INTERFACEVERSION_MT + EXODUS_INTERFACEVERSION_DLL + EXODUS_INTERFACEVERSION_DEBUG

#endif
